export const TMDB_BASE_URL = 'https://api.themoviedb.org/3'
export const TMDB_POSTER_BASE_URL = 'https://image.tmdb.org/t/p'
export const TMDB_FILMS_COLLECTION = 'films'
export const TMDB_FILMS_LIST_COLLECTION = 'filmLists'
export const TMDB_WATCH_HISTORY_COLLECTION = 'watchHistory'
